---
# handlers file for basic_setup
- name: restart ssh service
  service:
    name: ssh
    state: restarted

- name: ntpdate sync time now
  command: "ntpdate {{ ntpdate_server }}"

- name: restart systemd-resolved service
  service:
    name: systemd-resolved
    state: restarted