---
# defaults file for common

k8s:
    # 控制平面的 主机域名和端口号
    # ref: https://kubernetes.io/zh/docs/setup/production-environment/tools/kubeadm/high-availability/#%E4%BD%BF%E7%94%A8%E5%A0%86%E6%8E%A7%E5%88%B6%E5%B9%B3%E9%9D%A2%E5%92%8C-etcd-%E8%8A%82%E7%82%B9
    # kubeadm init --control-plane-endpoint "control_plane_dns:control_plane_port" ...(略)
    control_plane_dns: k8s.cluster.local
    control_plane_port: 6443
    # apiserver_advertise_address: 0.0.0.0
    apiserver_bind_port: 6443
    # ref: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network
    pod_network_cidr: "192.168.0.0/16"
    service_cidr: "10.96.0.0/12"
    service_dns_domain: "cluster.local"
    # 可选值: registry.cn-hangzhou.aliyuncs.com/google_containers  [官方文档](https://github.com/AliyunContainerService/sync-repo)
    # gcr.azk8s.cn/google_containers  [官方文档](http://mirror.azure.cn/help/gcr-proxy-cache.html)
    image_repository: "registry.cn-hangzhou.aliyuncs.com/google_containers"

apt:
    docker:
        apt_key_url: https://download.docker.com/linux/ubuntu/gpg
        apt_repository: https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu
    k8s:
        apt_key_url: https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg
        apt_repository: https://mirrors.aliyun.com/kubernetes/apt/


# master 节点个数
master_count: "{{ groups['master'] | length }}"
# 是否是单master模式
single_master: "{{ (groups['master'] | length) == 1 }}"
# 
first_master: "{{ groups['first_master'] | first }}"

ntpdate_server: cn.ntp.org.cn

docker:
  # daemon.json 配置, 参考: https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
  daemon:
    # Docker Hub镜像服务器
    registry-mirrors: 
      - https://dockerhub.azk8s.cn
      - https://docker.mirrors.ustc.edu.cn
      - https://reg-mirror.qiniu.com
    # 参考: https://kubernetes.io/zh/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#%E5%9C%A8%E6%8E%A7%E5%88%B6%E5%B9%B3%E9%9D%A2%E8%8A%82%E7%82%B9%E4%B8%8A%E9%85%8D%E7%BD%AE-kubelet-%E4%BD%BF%E7%94%A8%E7%9A%84-cgroup-%E9%A9%B1%E5%8A%A8%E7%A8%8B%E5%BA%8F
    exec-opts:
      - "native.cgroupdriver=systemd"

