---
- name: Create a load blance using HAproxy
  hosts: load_blance
  vars:
    service_bind_port: 6443
    backend_servers:
      # - "<ip>:<port>"
      - "192.168.3.154:8010"
      - "192.168.3.154:8020"
      - "192.168.3.155:8010"
      - "192.168.3.155:8020"
    ha_stats_enable: True
    ha_stats_port: 1936
    ha_stats_url: /haproxy_stats
    ha_stats_user: admin
    ha_stats_pwd: 9527
    
  tasks:
    - name: check parameters
      fail:
        msg: "Please setup backend_servers parameter"
      when: backend_servers[0] == '<ip>:<port>'

      # 进行主机的基础设置
    - import_role:
        name: basic_setup

    - name: install haproxy
      apt:
        update_cache: no
        pkg:
          - haproxy
        state: present

    # - name: add docker-ce GPG key
    #   apt_key:
    #     url: "{{ apt.docker.apt_key_url }}"
    #     state: present

    # - name: add docker-ce APT repository
    #   apt_repository:
    #     repo: "deb [arch=amd64] {{ apt.docker.apt_repository }} {{ ansible_lsb.codename }} stable"

    # - name: check if docker installed
    #   stat:
    #     path: /usr/bin/docker
    #   register: check_docker

    # - name: update apt cache if docker does not installed
    #   apt:
    #     update_cache: yes
    #   when: check_docker.stat.exists == False

    # - name: install docker-ce pkg
    #   apt:
    #     pkg:
    #       - docker-ce
    #       - docker-ce-cli
    #       - containerd.io

    # - name: setup /etc/docker/daemon.json
    #   json_patch:
    #     src: "/etc/docker/daemon.json"
    #     create: yes
    #     create_type: object
    #     pretty: yes
    #     operations:
    #       - op: add
    #         path: "/registry-mirrors"
    #         value: ["https://dockerhub.azk8s.cn"]
    #       - op: add
    #         path: "/exec-opts"
    #         value: ["native.cgroupdriver=systemd"]
    #   notify: restart docker service

    # - name: Check if docker-compose exists
    #   stat:
    #     path: /usr/local/bin/docker-compose
    #   register: docker_compose

    # - name: Install docker-compose
    #   shell:
    #     cmd: 'curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose'
    #     warn: false
    #   when: docker_compose.stat.exists == False
    
    - name: setup HAproxy configuration
      template:
        backup: True
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: u=rw,g=r,o=r
      notify: restart HAproxy service

  # handlers:
  #   - name: restart docker service
  #     service:
  #       name: docker
  #       state: restarted
  #   - name: restart HAproxy service
  #     service:
  #       name: haproxy
  #       state: restarted