---
- name: test
  hosts: lb_and_ha
  vars:
    service_bind_port: "{{ k8s.control_plane_port }}"
    backend_server_port: "{{ k8s.apiserver_bind_port }}"
    backend_servers: #"{{ ansible_play_hosts_all | map('regex_replace', '^(.*)$',  '\\1:' + backend_server_port) | list }}"
      # - "<ip>:<port>"
      # - "192.168.3.151:6443"
      # - "192.168.3.152:6443"
      # - "192.168.3.153:6443"
    
  tasks:
    # - name: check parameters
    #   fail:
    #     msg: "Please setup backend_servers parameter"
    #   when: backend_servers[0] == '<ip>:<port>'

      # 进行主机的基础设置
    - import_role:
        name: common

    - name: check parameters
      fail:
        msg: "Please setup backend_servers parameter"
      when: backend_servers == None or (backend_servers|count) == 0 or backend_servers[0] == '' or  backend_servers[0] == '<ip>:<port>'

    - debug:
        msg: "service_bind_port = {{ service_bind_port }}"

    - debug:
        msg: "backend_servers = {{ backend_servers }}"